name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      env:
        POETRY_VERSION: "1.7.1"
      run: curl -sSL https://install.python-poetry.org | python - -y
      shell: bash

    - name: Add Poetry to Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure Poetry virtual environment in project
      run: poetry config virtualenvs.in-project true
      shell: bash

    # Re-enable caching with improved key and restore logic
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        # Include poetry.toml in the cache key to catch configuration changes
        key: venv-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('poetry.lock', 'poetry.toml') }}-v2

    - name: Install dependencies
      run: |
        if [ "${{ steps.cached-poetry-dependencies.outputs.cache-hit }}" == 'true' ]; then
          echo "Using cached virtual environment"

          # Validate the cached environment contains expected tools
          if ! poetry run pre-commit --version &>/dev/null || \
             ! poetry run pytest --version &>/dev/null || \
             ! poetry run mypy --version &>/dev/null; then
            echo "Cached environment is missing required tools. Reinstalling..."
            rm -rf .venv
            poetry install --no-interaction --with dev
          fi
        else
          echo "Installing dependencies"
          rm -rf .venv || true
          poetry install --no-interaction --with dev
        fi
      shell: bash

    - name: Verify development tools installation
      run: |
        echo "Verifying pre-commit installation..."
        poetry run pre-commit --version
        echo "Verifying pytest installation..."
        poetry run pytest --version
        echo "Verifying mypy installation..."
        poetry run mypy --version
      shell: bash
